language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
sudo: false
before_script:
  - composer self-update
  - composer install
script:
 - ./vendor/bin/phpunit
